baseurl = "https://acppsn.netlify.app/"
languageCode = "zh-cn"
title = "Advanced C++ Seminar Notebook"
copyright = "&copy; CC0-1.0 License"


[params]
    github = "NeilKleistGao"
    author = "Advanced C++ Seminar"
    avatar = "/avatar.jpg"
    bio = "XD"
    subtitle = "当你拿着C++这把锤子，看什么都像钉子"
    themecolor = "#66CCFF" # Defines the tab color in Chrome for Android.